# Generated by Django 6.0.3 on 2026-03-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PropertyListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("onMarket", "Active"),
                            ("offMarket", "Off Market"),
                            ("membersOnlyShow", "Members Only - Show"),
                            ("membersOnlyDoNotShow", "Members Only - Do Not Show"),
                        ],
                        help_text="Current listing status",
                        max_length=25,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("bedrooms", models.PositiveIntegerField()),
                ("full_bathrooms", models.PositiveIntegerField()),
                ("half_bathrooms", models.PositiveIntegerField()),
                ("garage", models.PositiveIntegerField()),
                ("sqft", models.PositiveIntegerField()),
                ("sqft_lot", models.DecimalField(decimal_places=2, max_digits=12)),
                ("listing_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("age", models.PositiveIntegerField()),
                ("listing_agent", models.CharField(max_length=100)),
                ("listing_agent_office", models.CharField(max_length=150)),
                ("school_district", models.CharField(max_length=150)),
                ("arv", models.DecimalField(decimal_places=2, max_digits=12)),
                ("mls_number", models.CharField(blank=True, max_length=50, null=True)),
                ("dom", models.PositiveIntegerField(blank=True, null=True)),
                ("disclosures", models.TextField(blank=True, null=True)),
                ("open_house", models.CharField(blank=True, max_length=255, null=True)),
                ("private_notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Property Listing",
                "verbose_name_plural": "Properties Listings",
            },
        ),
    ]
