# Generated by Django 6.0.3 on 2026-03-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "active"),
                            ("Off Market", "off"),
                            ("Show", "show"),
                            ("Members Only Do Not Show", "donotshow"),
                        ],
                        help_text="Current listing status",
                        max_length=25,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("bedrooms", models.PositiveIntegerField()),
                ("full_bathrooms", models.PositiveIntegerField()),
                ("half_bathrooms", models.PositiveIntegerField()),
                ("garage", models.PositiveIntegerField()),
                ("sqft", models.PositiveIntegerField()),
                ("sqft_lot", models.DecimalField(decimal_places=2, max_digits=12)),
                ("listing_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("age", models.PositiveIntegerField()),
                ("listing_agent", models.CharField(max_length=100)),
                ("listing_agent_office", models.CharField(max_length=150)),
                ("school_district", models.CharField(max_length=150)),
                ("arv", models.DecimalField(decimal_places=2, max_digits=12)),
                ("mls_number", models.CharField(blank=True, max_length=50, null=True)),
                ("dom", models.PositiveIntegerField(blank=True, null=True)),
                ("disclosures", models.TextField(blank=True, null=True)),
                ("open_house", models.CharField(blank=True, max_length=255, null=True)),
                ("private_notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Property Template",
                "verbose_name_plural": "Properties Templates",
            },
        ),
        migrations.DeleteModel(
            name="PropertyListing",
        ),
    ]
