# Generated by Django 6.0.3 on 2026-04-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0002_template_delete_propertylisting"),
    ]

    operations = [
        migrations.RenameField(
            model_name="template",
            old_name="full_bathrooms",
            new_name="fullBathrooms",
        ),
        migrations.RenameField(
            model_name="template",
            old_name="half_bathrooms",
            new_name="halfBathrooms",
        ),
        migrations.RenameField(
            model_name="template",
            old_name="listing_agent",
            new_name="listingAgent",
        ),
        migrations.RenameField(
            model_name="template",
            old_name="listing_agent_office",
            new_name="listingAgentOffice",
        ),
        migrations.RenameField(
            model_name="template",
            old_name="listing_price",
            new_name="listingPrice",
        ),
        migrations.RenameField(
            model_name="template",
            old_name="mls_number",
            new_name="mlsNumber",
        ),
        migrations.RenameField(
            model_name="template",
            old_name="open_house",
            new_name="openHouse",
        ),
        migrations.RenameField(
            model_name="template",
            old_name="private_notes",
            new_name="privateNotes",
        ),
        migrations.RenameField(
            model_name="template",
            old_name="school_district",
            new_name="schoolDistrict",
        ),
        migrations.RenameField(
            model_name="template",
            old_name="sqft_lot",
            new_name="sqftLot",
        ),
        migrations.AlterField(
            model_name="template",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("off", "Off Market"),
                    ("show", "Members Only Show"),
                    ("donotshow", "Members Only Do Not Show"),
                ],
                help_text="Current listing status",
                max_length=25,
            ),
        ),
    ]
